// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/linktracker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterChatRequest) Reset() {
	*x = RegisterChatRequest{}
	mi := &file_proto_linktracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChatRequest) ProtoMessage() {}

func (x *RegisterChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChatRequest.ProtoReflect.Descriptor instead.
func (*RegisterChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type RegisterChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterChatResponse) Reset() {
	*x = RegisterChatResponse{}
	mi := &file_proto_linktracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChatResponse) ProtoMessage() {}

func (x *RegisterChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChatResponse.ProtoReflect.Descriptor instead.
func (*RegisterChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{1}
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_proto_linktracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type DeleteChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatResponse) Reset() {
	*x = DeleteChatResponse{}
	mi := &file_proto_linktracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatResponse) ProtoMessage() {}

func (x *DeleteChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{3}
}

type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_proto_linktracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{4}
}

func (x *ListLinksRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type AddLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Filters       []string               `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinkRequest) Reset() {
	*x = AddLinkRequest{}
	mi := &file_proto_linktracker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinkRequest) ProtoMessage() {}

func (x *AddLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinkRequest.ProtoReflect.Descriptor instead.
func (*AddLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{5}
}

func (x *AddLinkRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *AddLinkRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *AddLinkRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AddLinkRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type RemoveLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLinkRequest) Reset() {
	*x = RemoveLinkRequest{}
	mi := &file_proto_linktracker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLinkRequest) ProtoMessage() {}

func (x *RemoveLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLinkRequest.ProtoReflect.Descriptor instead.
func (*RemoveLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveLinkRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *RemoveLinkRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type LinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Filters       []string               `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkResponse) Reset() {
	*x = LinkResponse{}
	mi := &file_proto_linktracker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkResponse) ProtoMessage() {}

func (x *LinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkResponse.ProtoReflect.Descriptor instead.
func (*LinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{7}
}

func (x *LinkResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LinkResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LinkResponse) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*LinkResponse        `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_proto_linktracker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{8}
}

func (x *ListLinksResponse) GetLinks() []*LinkResponse {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ListLinksResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ApiErrorResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Description      string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Code             string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	ExceptionName    string                 `protobuf:"bytes,3,opt,name=exception_name,json=exceptionName,proto3" json:"exception_name,omitempty"`
	ExceptionMessage string                 `protobuf:"bytes,4,opt,name=exception_message,json=exceptionMessage,proto3" json:"exception_message,omitempty"`
	Stacktrace       []string               `protobuf:"bytes,5,rep,name=stacktrace,proto3" json:"stacktrace,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApiErrorResponse) Reset() {
	*x = ApiErrorResponse{}
	mi := &file_proto_linktracker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiErrorResponse) ProtoMessage() {}

func (x *ApiErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiErrorResponse.ProtoReflect.Descriptor instead.
func (*ApiErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{9}
}

func (x *ApiErrorResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApiErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApiErrorResponse) GetExceptionName() string {
	if x != nil {
		return x.ExceptionName
	}
	return ""
}

func (x *ApiErrorResponse) GetExceptionMessage() string {
	if x != nil {
		return x.ExceptionMessage
	}
	return ""
}

func (x *ApiErrorResponse) GetStacktrace() []string {
	if x != nil {
		return x.Stacktrace
	}
	return nil
}

type LinkUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TgChatIds     []int64                `protobuf:"varint,4,rep,packed,name=tg_chat_ids,json=tgChatIds,proto3" json:"tg_chat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkUpdate) Reset() {
	*x = LinkUpdate{}
	mi := &file_proto_linktracker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUpdate) ProtoMessage() {}

func (x *LinkUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUpdate.ProtoReflect.Descriptor instead.
func (*LinkUpdate) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{10}
}

func (x *LinkUpdate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LinkUpdate) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LinkUpdate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LinkUpdate) GetTgChatIds() []int64 {
	if x != nil {
		return x.TgChatIds
	}
	return nil
}

type SendUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUpdateResponse) Reset() {
	*x = SendUpdateResponse{}
	mi := &file_proto_linktracker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUpdateResponse) ProtoMessage() {}

func (x *SendUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linktracker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUpdateResponse.ProtoReflect.Descriptor instead.
func (*SendUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_linktracker_proto_rawDescGZIP(), []int{11}
}

var File_proto_linktracker_proto protoreflect.FileDescriptor

const file_proto_linktracker_proto_rawDesc = "" +
	"\n" +
	"\x17proto/linktracker.proto\x12\x0elinktracker.v1\".\n" +
	"\x13RegisterChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"\x16\n" +
	"\x14RegisterChatResponse\",\n" +
	"\x11DeleteChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"\x14\n" +
	"\x12DeleteChatResponse\"+\n" +
	"\x10ListLinksRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"k\n" +
	"\x0eAddLinkRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x18\n" +
	"\afilters\x18\x04 \x03(\tR\afilters\"@\n" +
	"\x11RemoveLinkRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\"^\n" +
	"\fLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x18\n" +
	"\afilters\x18\x04 \x03(\tR\afilters\"[\n" +
	"\x11ListLinksResponse\x122\n" +
	"\x05links\x18\x01 \x03(\v2\x1c.linktracker.v1.LinkResponseR\x05links\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\xbc\x01\n" +
	"\x10ApiErrorResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12%\n" +
	"\x0eexception_name\x18\x03 \x01(\tR\rexceptionName\x12+\n" +
	"\x11exception_message\x18\x04 \x01(\tR\x10exceptionMessage\x12\x1e\n" +
	"\n" +
	"stacktrace\x18\x05 \x03(\tR\n" +
	"stacktrace\"p\n" +
	"\n" +
	"LinkUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\vtg_chat_ids\x18\x04 \x03(\x03R\ttgChatIds\"\x14\n" +
	"\x12SendUpdateResponse2\xab\x03\n" +
	"\x0fScrapperService\x12Y\n" +
	"\fRegisterChat\x12#.linktracker.v1.RegisterChatRequest\x1a$.linktracker.v1.RegisterChatResponse\x12S\n" +
	"\n" +
	"DeleteChat\x12!.linktracker.v1.DeleteChatRequest\x1a\".linktracker.v1.DeleteChatResponse\x12P\n" +
	"\tListLinks\x12 .linktracker.v1.ListLinksRequest\x1a!.linktracker.v1.ListLinksResponse\x12G\n" +
	"\aAddLink\x12\x1e.linktracker.v1.AddLinkRequest\x1a\x1c.linktracker.v1.LinkResponse\x12M\n" +
	"\n" +
	"RemoveLink\x12!.linktracker.v1.RemoveLinkRequest\x1a\x1c.linktracker.v1.LinkResponse2Z\n" +
	"\n" +
	"BotService\x12L\n" +
	"\n" +
	"SendUpdate\x12\x1a.linktracker.v1.LinkUpdate\x1a\".linktracker.v1.SendUpdateResponseBWZUgitlab.education.tbank.ru/backend-academy-go-2026/homeworks/link-tracker/shared/pb;pbb\x06proto3"

var (
	file_proto_linktracker_proto_rawDescOnce sync.Once
	file_proto_linktracker_proto_rawDescData []byte
)

func file_proto_linktracker_proto_rawDescGZIP() []byte {
	file_proto_linktracker_proto_rawDescOnce.Do(func() {
		file_proto_linktracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_linktracker_proto_rawDesc), len(file_proto_linktracker_proto_rawDesc)))
	})
	return file_proto_linktracker_proto_rawDescData
}

var file_proto_linktracker_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_linktracker_proto_goTypes = []any{
	(*RegisterChatRequest)(nil),  // 0: linktracker.v1.RegisterChatRequest
	(*RegisterChatResponse)(nil), // 1: linktracker.v1.RegisterChatResponse
	(*DeleteChatRequest)(nil),    // 2: linktracker.v1.DeleteChatRequest
	(*DeleteChatResponse)(nil),   // 3: linktracker.v1.DeleteChatResponse
	(*ListLinksRequest)(nil),     // 4: linktracker.v1.ListLinksRequest
	(*AddLinkRequest)(nil),       // 5: linktracker.v1.AddLinkRequest
	(*RemoveLinkRequest)(nil),    // 6: linktracker.v1.RemoveLinkRequest
	(*LinkResponse)(nil),         // 7: linktracker.v1.LinkResponse
	(*ListLinksResponse)(nil),    // 8: linktracker.v1.ListLinksResponse
	(*ApiErrorResponse)(nil),     // 9: linktracker.v1.ApiErrorResponse
	(*LinkUpdate)(nil),           // 10: linktracker.v1.LinkUpdate
	(*SendUpdateResponse)(nil),   // 11: linktracker.v1.SendUpdateResponse
}
var file_proto_linktracker_proto_depIdxs = []int32{
	7,  // 0: linktracker.v1.ListLinksResponse.links:type_name -> linktracker.v1.LinkResponse
	0,  // 1: linktracker.v1.ScrapperService.RegisterChat:input_type -> linktracker.v1.RegisterChatRequest
	2,  // 2: linktracker.v1.ScrapperService.DeleteChat:input_type -> linktracker.v1.DeleteChatRequest
	4,  // 3: linktracker.v1.ScrapperService.ListLinks:input_type -> linktracker.v1.ListLinksRequest
	5,  // 4: linktracker.v1.ScrapperService.AddLink:input_type -> linktracker.v1.AddLinkRequest
	6,  // 5: linktracker.v1.ScrapperService.RemoveLink:input_type -> linktracker.v1.RemoveLinkRequest
	10, // 6: linktracker.v1.BotService.SendUpdate:input_type -> linktracker.v1.LinkUpdate
	1,  // 7: linktracker.v1.ScrapperService.RegisterChat:output_type -> linktracker.v1.RegisterChatResponse
	3,  // 8: linktracker.v1.ScrapperService.DeleteChat:output_type -> linktracker.v1.DeleteChatResponse
	8,  // 9: linktracker.v1.ScrapperService.ListLinks:output_type -> linktracker.v1.ListLinksResponse
	7,  // 10: linktracker.v1.ScrapperService.AddLink:output_type -> linktracker.v1.LinkResponse
	7,  // 11: linktracker.v1.ScrapperService.RemoveLink:output_type -> linktracker.v1.LinkResponse
	11, // 12: linktracker.v1.BotService.SendUpdate:output_type -> linktracker.v1.SendUpdateResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_linktracker_proto_init() }
func file_proto_linktracker_proto_init() {
	if File_proto_linktracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_linktracker_proto_rawDesc), len(file_proto_linktracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_linktracker_proto_goTypes,
		DependencyIndexes: file_proto_linktracker_proto_depIdxs,
		MessageInfos:      file_proto_linktracker_proto_msgTypes,
	}.Build()
	File_proto_linktracker_proto = out.File
	file_proto_linktracker_proto_goTypes = nil
	file_proto_linktracker_proto_depIdxs = nil
}
