FROM golang:1.25.2 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/scrapper ./cmd/scrapper

FROM alpine:3.21.3

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY --from=builder /bin/scrapper /app/scrapper

CMD ["./scrapper"]
